### ISSUE TITLE
Bug in CSP setting

### ISSUE THREAD

**Issue by kim-dali** [sejong-opensource/moti#1]
![image](https://user-images.githubusercontent.com/40654172/117318640-9108de80-aec5-11eb-95e0-10b880b23e38.png)
다음과 같이 menifest.json 에서 default로 csp를 설정하면 보안 규칙상 빌드된 파일이 제대로 동작하지 않습니다.
해당 문제가 해결되어야 익스텐션 환경에서 원활하게 진행할 수 있기에 팀원분들도 함께 방법을 찾아보면 좋을 것 같습니다.

**Comment by yunseo323** [comment]
yarn start 로 생성된  dist 폴더를 연결해야 함
개발이 완료된 후  build 폴더 생성하기
