### ISSUE TITLE
dashboard css

### ISSUE THREAD

**Issue by yunseo323** [sejong-opensource/moti#8]
- background를 기존에 정했던 보라색이 아닌, 사진으로 대체
- 배치 변경 : 투두리스트가 세로로 길어야함

**Comment by kim-dali** [comment]
- newtab 의 페이지에서 스크롤 기능이 필요 없도록 한 페이지에 들어오게 되면 좋을 것 같으며, 투두리스트나 이메일리스트가 길어진다면 해당 리스트에만 스크롤을 적용하면 좋을 것 같습니다!

**Comment by yunseo323** [comment]
background를 사진 보다 그라데이션 색을 넣는 것으로 변경
